### ISSUE TITLE
encode.lua output directory?

### ISSUE THREAD

**Issue by frozenpandaman** [occivink/mpv-scripts#11]
I can't find where the result of the encode.lua command gets output to (if anywhere, at the moment?). I'm running one of the "OS X builds by stolendata" (https://mpv.io/installation/), not the command line version of mpv. ffmpeg (installed via Homebrew) is in my PATH. The "Encoding from … to …" message goes away which makes me think it was successful, but I'm not sure where to see the result/output.

Relatedly, can the output directory be changed/set on a per-profile basis, i.e. in a .conf file in lua-settings/? Thanks!

**Comment by occivink** [comment]
Hi,
Yes the output directory is configurable using the option detailed [here](https://github.com/occivink/mpv-scripts/blob/master/lua-settings/encode_webm.conf#L26-L29). 

Unfortunately the message is not necessarily a good indicator as to whether the script is working. What you can do is set `detached=no`, in which case you will get a (relatively terse) message indicating the result (either `Finished encoding succesfully` or `Failed to encode, check the log`). 
Note that if detached is set to yes (which has its advantages) we don't output anything, since we don't know the result at all.

Finally if you launch mpv from the terminal, the script should also print in the console the exact ffmpeg command that is run, so that you can analyze it, or simply copy and paste it to troubleshoot it.

**Comment by frozenpandaman** [comment]
Not sure how I missed that… thanks for pointing it out, and for your speedy reply as well. :) Yeah, I noticed that in your demo video – useful! Thanks again.

**Comment by occivink** [comment]
Well I'm happy you did, because it made me discover your Kaiba revised script.

**Comment by frozenpandaman** [comment]
heh. i'm so happy to hear that. thanks for telling me :) i hope you find it useful!

love yuasa's work so so much. (i've been meaning to rewatch it soon, as well, so thanks for reminding me on that front…!)

**Comment by frozenpandaman** [comment]
Also just a note that the `"`s at
https://github.com/occivink/mpv-scripts/blob/9228f67bb18adcb27775bd3be927510f6efea0e7/lua-settings/encode_slice.conf#L8
actually get written out as part of the filename which probably isn't intended. They're not present in the sample in the other example (encode_webm.conf) either. Not that big of an issue though.
