### ISSUE TITLE
Change formatting of start and end time in file name

### ISSUE THREAD

**Issue by joeynotjoe** [occivink/mpv-scripts#21]
I tried looking through the code to find where I might be able to change it, but was unable to do so successfully. 

Basically, I would love to be able to change the start time and end time formatting to use periods as separators, instead of colons, in the file name.

Is there somewhere easy to do this in the script?

**Comment by occivink** [comment]
The formatting code uses [this function](https://github.com/occivink/mpv-scripts/blob/master/scripts/encode.lua#L116), you can simply change the columns to periods.
However, if you do so you should also change [this line](https://github.com/occivink/mpv-scripts/blob/master/scripts/encode.lua#L137) to ` "-ss", tostring(from),` otherwise ffmpeg won't understand the timestring syntax.

**Comment by joeynotjoe** [comment]
Aha, perfect. The second part was my problem. Sincerely thank you for your assistance!
